#! /bin/bash
# The line above tells this script to be interpreted as a bash script when run from the command line.

# Make sure, we can add extra repositories
sudo apt-get --yes --force-yes install software-properties-common

# Add repository for Zeal documentation browser
sudo add-apt-repository ppa:zeal-developers/ppa

# Add repository for Atom editor
sudo add-apt-repository ppa:webupd8team/atom

# Update of package information
sudo apt-get update

# Update all installed packages to ensure all security updates are obtained
sudo apt-get --yes --force-yes dist-upgrade

# Installation of Google Chromium as second browser
sudo apt-get --yes --force-yes install chromium-browser

# We enable the firewall, because we will install server applications afterwards
sudo ufw enable

# Ruby prerequesites and tools: Bash, Curl, Git, C Compiler, OpenSSL, MySQL, Terminator, PostgresQL and several more
sudo apt-get --yes --force-yes install bash curl git-core build-essential bison openssl libreadline6 libreadline6-dev zlib1g 
sudo apt-get --yes --force-yes install zlib1g-dev libssl-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev curl git-core
sudo apt-get --yes --force-yes install libyaml-dev libxslt-dev autoconf libmysqlclient-dev libreadline5 libltdl-dev
sudo apt-get --yes --force-yes install libncurses5-dev libserf1-dbg libsvn1 libtool subversion libgdbm-dev pkg-config 
sudo apt-get --yes --force-yes install libffi-dev libgmp3-dev terminator libpq-dev postgresql-client postgresql
sudo apt-get --yes --force-yes install postgresql-contrib pgadmin3

# We install rvm by first installing their public ssh-key
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
# and then rvm itself
\curl -sSL https://get.rvm.io | bash
# Some Ubuntu flavours need more help sourcing rvm from termanials, but only if it's not already there
grep -q -F '/.rvm/scripts/rvm' ~/.bashrc || echo "source /home/$(whoami)/.rvm/scripts/rvm" >> ~/.bashrc
# Furthermore we need to load it on the fly
source /home/$(whoami)/.rvm/scripts/rvm

# Let's install Ruby 2.1, 2.2 and 2.3
rvm install ruby-2.1
rvm install ruby-2.2
rvm install ruby-2.3

# We install bundler, 
rvm use 2.1
# .. latest Rails 3, ...
gem install rails:'<4'
# ... database support for SQLite, PostgresQL and MySQL, ...
gem install bundler sqlite3 pg mysql2 
# ... devise (authorization gem) and paperclip (attachment upload gem)
gem install devise paperclip

# The same for Ruby 2.2, ...
rvm use 2.2
# .. but with latest Rails 4.
gem install rails:'<4'
gem install bundler sqlite3 pg mysql2 
gem install devise paperclip

# And one more time with Ruby 2.3, ...
rvm use 2.3
# .. but with latest Rails 5.
gem install rails -v "5.0.0.beta2"
gem install bundler sqlite3 pg mysql2 
gem install devise paperclip

# Let's install Apache, MySQL and OpenSSH-Server, if we want to share data
sudo apt-get --yes --force-yes install apache2 mysql-server phpmyadmin openssh-server mysql-client

# Let's install Zeal and a sane amount of documentation
# well, if I only knew how to install docsets from the console ...
sudo apt-get --yes --force-yes install zeal

# Let's install Atom editor
sudo apt-get --yes --force-yes install atom

# We set latest stable Ruby, i.e. 2.3 as default
rvm --default use 2.3
