#! /bin/bash
# The line above tells this script to be interpreted as a bash script when run from the command line.

echo -e "\n\e[96m === Downloading Docsets ... ===\e[0m"
cd ~/.local/share/Zeal/Zeal/docsets

if [ -d ~/.local/share/Zeal/Zeal/docsets/Ruby\ on\ Rails\ 3.docset ]
  then
    echo -e "\n\e[96m === ... docsets for Rails 3 already installed ===\e[0m"
  else
    echo -e "\n\e[96m === ... docsets for Rails 3 ===\e[0m"
    wget http://london.kapeli.com/feeds/Ruby_on_Rails_3.tgz
    tar -xvzf Ruby_on_Rails_3.tgz
    mv "Ruby on Rails.docset" "Ruby on Rails 3.docset"
    rm ~/.local/share/Zeal/Zeal/docsets/Ruby_on_Rails_3.tgz
fi

if [ -d ~/.local/share/Zeal/Zeal/docsets/Ruby\ on\ Rails\ 4.docset ]
  then
    echo -e "\n\e[96m === ... docsets for Rails 4 already installed ===\e[0m"
  else
    echo -e "\n\e[96m === ... docsets for Rails 4 ===\e[0m"
    wget http://london.kapeli.com/feeds/Ruby_on_Rails_4.tgz
    tar -xvzf Ruby_on_Rails_4.tgz
    mv "Ruby on Rails.docset" "Ruby on Rails 4.docset"
    rm ~/.local/share/Zeal/Zeal/docsets/Ruby_on_Rails_4.tgz
fi

if [ -d ~/.local/share/Zeal/Zeal/docsets/Ruby\ on\ Rails\ 5.docset ]
  then
    echo -e "\n\e[96m === ... docsets for Rails 5 already installed ===\e[0m"
  else
    echo -e "\n\e[96m === ... docsets for Rails 5 ===\e[0m"
    wget http://london.kapeli.com/feeds/Ruby_on_Rails_5.tgz
    tar -xvzf Ruby_on_Rails_5.tgz
    mv "Ruby on Rails.docset" "Ruby on Rails 5.docset"
    rm ~/.local/share/Zeal/Zeal/docsets/Ruby_on_Rails_5.tgz
fi
